---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubetoy
  namespace: app-kubetoy-project
  labels:
    app: kubetoy
    team: team1
    catagory: webapp
spec:
  selector:
    matchLabels:
      app: kubetoy
      team: team1
      catagory: webapp
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: app-kubetoy-prod
  namespace: app-kubetoy-project
  labels:
    app: kubetoy
    team: team1
    catagory: webapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cluster: managed-app-cluster
      environment: PROD
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: app-kubetoy-subsciption
  namespace: app-kubetoy-project
  labels:
    app: kubetoy
    team: team1
    catagory: webapp
spec:
  channel: app-kubetoy-entitlement/app-kubetoy-channel
  name: ""
  packageFilter:
    labelSelector:  # to match target deployables or a subset of a deployables
      matchLabels:
        app: kubetoy
        team: team1
        catagory: webapp
  placement:
    placementRef:
      name: app-kubetoy-prod
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default
