---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: app-sushi
  namespace: app-sushi-project
  labels:
    app: app-sushi
    team: team1
    catagory: webapp
spec:
  channel: app-sushi-entitlement/app-sushi
  name: ""
  packageFilter:
    labelSelector:  # to match target deployables or a subset of a deployables
      matchLabels:
        app: app-sushi
        team: team1
        catagory: webapp
  placement:
    placementRef:
      name: app-sushi-prod
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-sushi
  namespace: app-sushi-project
  labels:
    app: app-sushi
    team: team1
    catagory: webapp
spec:
  selector:
    matchLabels:
      app: app-sushi
      team: team1
      catagory: webapp
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: app-sushi-prod
  namespace: app-sushi-project
  labels:
    app: app-sushi
    team: team1
    catagory: webapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cluster: managed-app-cluster
      environment: PROD
